### These notes are based on the "Generating Random Data in Python (Guide)" available at: https://realpython.com/python-random/

In [117]:
import random
import numpy as np
import os
import secrets
import uuid

## PRNG 

### Not-So-Random PRNG

Input A always produces output B

In [10]:
class NotSoRandom(object):
    def __init__(self, seed_val=1234):
        self.seed_val = seed_val
    def random(self):
        random_number = (self.seed_val * 18) % 221
        return(random_number)

In [15]:
rand_inst = NotSoRandom(seed_val=123)
random_number = rand_inst.random()
random_number

4

In [28]:
random.seed(1234)
[random.randint(0, 9) for _ in range(10)]

[7, 1, 0, 1, 9, 0, 1, 1, 5, 3]

In [27]:
random.seed(1234)
[random.randint(0, 9) for _ in range(10)]

[7, 1, 0, 1, 9, 0, 1, 1, 5, 3]

### Python's random module 

See also: [Mersenne Twister](https://en.wikipedia.org/wiki/Mersenne_Twister)

The `random.random()` function returs a random float in the interval [0.0, 1.0)

In [29]:
random.random()

0.017428048184618405

The `random.randint()` function spans the full [x, y] interval to return an integer (may include both endpoints)

In [33]:
random.randint(0, 10)

9

The `random.randrange()` generates an integer that lies in [x, y)

docs: "This fixes the problem with randint() which includes the
endpoint; in Python this is usually not what you want."

In [36]:
random.randrange(1, 10)

8

The `random.uniform()` function generates a random float in [x, y]

In [38]:
random.uniform(0, 10)

1.4855463870828756

`random.choice()` picks a single element from a non-empty list/tuple

In [93]:
items = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
random.choice(items)

12

`random.choice`**`s`**`()` picks multiple elements from a sequence with replacement duplicates

In [42]:
random.choices(items, k=3)

[17, 19, 15]

`random.sample()` mimics sampling without replacement

In [43]:
random.sample(items, 4)

[13, 11, 18, 17]

`random.shuffle()` permutes a sequence in-place

In [45]:
random.shuffle(items)
items

[18, 13, 20, 12, 15, 14, 11, 10, 19, 16, 17]

See for example: https://stackoverflow.com/questions/48421142/fastest-way-to-generate-a-random-like-unique-string-with-random-length-in-python/48421303#48421303

### `numpy.random`

In [48]:
np.random.seed(444)
np.random.randn(5)

array([ 0.35743992,  0.3775384 ,  1.38233789,  1.17554883, -0.9392757 ])

In [50]:
np.random.seed(444)
np.random.randn(5)

array([ 0.35743992,  0.3775384 ,  1.38233789,  1.17554883, -0.9392757 ])

It's  **faster** to choose from (0, 1) and then view-cast these integers to their corresponding Boolena values than to call `np.random.choice([True, False])`

In [75]:
%time np.random.randint(0, 2, size=10000, dtype=np.uint8).view(bool)

CPU times: user 93 µs, sys: 0 ns, total: 93 µs
Wall time: 52.9 µs


array([False, False,  True, ..., False,  True,  True])

In [76]:
%time np.random.choice([True, False], size=10000)

CPU times: user 221 µs, sys: 79 µs, total: 300 µs
Wall time: 202 µs


array([ True,  True,  True, ...,  True, False,  True])

`np.random.rand()`: Random float in [0.0, 1.0)

In [77]:
np.random.rand()

0.17360318468139657

`np.random.random_integers()`: Random integer in [x, y]

In [78]:
np.random.random_integers(10, 20)

/home/shreya/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  """Entry point for launching an IPython kernel.


12

`np.random.randint()`: Random integer in [x, y)

In [82]:
np.random.randint(10, 20 + 1)

16

`np.random.uniform()`: Random float in [x, y]

In [84]:
np.random.uniform(10, 20)

12.688597391083473

`np.random.choice()`: Random *k* elements from `seq` without replacement

In [86]:
np.random.choice(items, size=2)

array([20, 13])

`np.random.choice(, replace=False)`: Random *k* elements from `seq` without replacement

In [87]:
np.random.choice(items, size=2, replace=False)

array([17, 10])

`np.random.shuffle()`: Shuffle the sequence *x* in place

In [95]:
np.random.shuffle(items)
items

[15, 10, 13, 18, 14, 12, 16, 11, 20, 17, 19]

`np.random.normal()`: Sample from a normal distribution with mean $\mu$ and standard deviation $\sigma$

In [96]:
np.random.normal()

-1.143150147501205

## CSPRNG

`os.urandom()` generates operating system dependent random bytes suitable for cryptographic use.

On Unix operating systems, it reads random bytes from the special file /dev/urandom, which in turn “allow access to environmental noise collected from device drivers and other sources.” This is garbled information that is particular to your hardware and system state at an instance in time but at the same time sufficiently random.

See aslo: https://en.wikipedia.org/wiki//dev/random

In [104]:
x = os.urandom(10)
x

b'\x96\x7fj=9n\x98J\xc5\xd9'

In [106]:
type(x), len(x)

(bytes, 10)

In [111]:
list(x)

[150, 127, 106, 61, 57, 110, 152, 74, 197, 217]

### `secrets` module 

In [114]:
secrets.token_bytes(nbytes=16)

b'\xe6\xf3{\xfd\xc3\xb0CM\xdb\xba\x84(\x11\xf3\xe6q'

In [115]:
secrets.token_hex(nbytes=16)

'40f29cd0fb7cd1be9b6b6fe3d687e3c5'

In [116]:
secrets.choice('rain')

'i'

## `uuid` module

A UUID is a Universally Unique IDentifier, a 128-bit sequence (str of length 32) designed to “guarantee uniqueness across space and time.”

In [119]:
tok = uuid.uuid4()
tok.bytes

b'\x95O7\x0cpsD\xa2\xb9\x9bn#\xfeNm\x87'